services:
  mq-thinktalk:
    build:
      context: .
      dockerfile: Dockerfile
    image: mq-thinktalk:latest
    container_name: mq-thinktalk
    restart: unless-stopped
    volumes:
      - ./etc:/app/etc
    environment:
      - ETCD_ENDPOINTS=10.8.0.1:2379
    networks:
      - thinktalk-net

networks:
  thinktalk-net:
    driver: bridge
